import{a as m,S as v,i as s}from"./assets/vendor-DcHCnVjq.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const P="56000261-e01ddd2b57ba4d59eaee941aa";m.defaults.baseURL="https://pixabay.com/api/";async function f(t,o=1){return(await m.get("",{params:{key:P,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}const g=document.querySelector(".gallery"),p=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function y(t){const o=t.map(({webformatURL:a,largeImageURL:l,tags:e,likes:r,views:n,comments:S,downloads:q})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${l}">
        <img class="gallery-image" src="${a}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${r}</p>
        <p class="info-item"><b>Views:</b> ${n}</p>
        <p class="info-item"><b>Comments:</b> ${S}</p>
        <p class="info-item"><b>Downloads:</b> ${q}</p>
      </div>
    </li>
  `).join("");g.insertAdjacentHTML("beforeend",o),E.refresh()}function $(){g.innerHTML=""}function b(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}function w(){h.classList.remove("hidden")}function u(){h.classList.add("hidden")}let c="",i=1,d=0;const M=document.querySelector(".form"),R=document.querySelector(".load-more-btn");M.addEventListener("submit",async t=>{t.preventDefault();const o=t.currentTarget;if(c=o.elements.searchQuery.value.trim(),c===""){s.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}i=1,$(),u(),b();try{const a=await f(c,i);if(d=a.totalHits,a.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(a.hits),d>i*15&&w()}catch{s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),o.reset()}});R.addEventListener("click",async()=>{i+=1,u(),b();try{const t=await f(c,i);if(d=t.totalHits,t.hits.length===0){s.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits),d<=i*15?(u(),s.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch(t){s.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(t)}finally{L(),form.reset()}});
//# sourceMappingURL=index.js.map
