import{a as m,S as q,i}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&l(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const E="56000261-e01ddd2b57ba4d59eaee941aa";m.defaults.baseURL="https://pixabay.com/api/";async function f(s,t=1){return(await m.get("",{params:{key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),P=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(s){const t=s.map(({webformatURL:o,largeImageURL:l,tags:e,likes:r,views:n,comments:v,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${l}">
        <img class="gallery-image" src="${o}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${r}</p>
        <p class="info-item"><b>Views:</b> ${n}</p>
        <p class="info-item"><b>Comments:</b> ${v}</p>
        <p class="info-item"><b>Downloads:</b> ${S}</p>
      </div>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",t),P.refresh()}function R(){p.innerHTML=""}function b(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function w(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}let c="",a=1,u=0;const $=document.querySelector(".form"),B=document.querySelector(".load-more-btn");$.addEventListener("submit",async s=>{s.preventDefault();const t=s.currentTarget;if(c=t.elements.searchQuery.value.trim(),c===""){i.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}a=1,R(),d(),b();try{const o=await f(c,a);if(u=o.totalHits,o.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(o.hits),u<=a*15?(d(),i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch(o){i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}finally{L(),t.reset()}});B.addEventListener("click",async()=>{a+=1,d(),b();try{const s=await f(c,a);y(s.hits);const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}a*15>=u?(d(),i.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch(s){i.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error(s)}finally{L()}});
//# sourceMappingURL=index.js.map
