import{a as m,S as q,i as n}from"./assets/vendor-DcHCnVjq.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))l(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&l(s)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function l(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const E="56000261-e01ddd2b57ba4d59eaee941aa";m.defaults.baseURL="https://pixabay.com/api/";async function f(o,t=1){return(await m.get("",{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}const p=document.querySelector(".gallery"),g=document.querySelector(".loader"),h=document.querySelector(".load-more-btn"),P=new q(".gallery a",{captionsData:"alt",captionDelay:250});function y(o){const t=o.map(({webformatURL:a,largeImageURL:l,tags:e,likes:r,views:s,comments:v,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${l}">
        <img class="gallery-image" src="${a}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${r}</p>
        <p class="info-item"><b>Views:</b> ${s}</p>
        <p class="info-item"><b>Comments:</b> ${v}</p>
        <p class="info-item"><b>Downloads:</b> ${S}</p>
      </div>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",t),P.refresh()}function $(){p.innerHTML=""}function b(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function w(){h.classList.remove("hidden")}function d(){h.classList.add("hidden")}let c="",i=1,u=0;const B=document.querySelector(".form"),M=document.querySelector(".load-more-btn");B.addEventListener("submit",async o=>{o.preventDefault();const t=o.currentTarget;if(c=t.elements.searchQuery.value.trim(),c===""){n.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}i=1,$(),d(),b();try{const a=await f(c,i);if(u=a.totalHits,a.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(a.hits),u>i*15&&w()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),t.reset()}});M.addEventListener("click",async()=>{i+=1,d(),b();try{const o=await f(c,i);y(o.hits),i*15>=u?(d(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w();const t=document.querySelector(".gallery-item");if(t){const a=t.getBoundingClientRect().height;window.scrollBy({top:a*2,behavior:"smooth"})}}catch(o){n.error({title:"Error",message:"Failed to load more images.",position:"topRight"}),console.error(o)}finally{L()}});
//# sourceMappingURL=index.js.map
